// src/app/api/auth/verify-otp/route.js
// OTP Verification (signed-token check) + Real Supabase Session Minting

import { NextResponse } from 'next/server';
import crypto from 'crypto';
import { createClient } from '@supabase/supabase-js';
import { createWriteClient } from '@/lib/supabase-bearer';

const MSG91_AUTH_KEY = (process.env.MSG91_AUTH_KEY || '').trim();

function signOtp(mobile, otp, expiry) {
  return crypto
    .createHmac('sha256', MSG91_AUTH_KEY)
    .update(`${mobile}.${otp}.${expiry}`)
    .digest('hex');
}

function verifyOtpToken(otpToken, mobile, otp) {
  try {
    const parsed = JSON.parse(Buffer.from(otpToken, 'base64').toString('utf8'));
    if (!parsed || parsed.m !== mobile) return { ok: false, reason: 'Invalid OTP session. Request a new code.' };
    if (Date.now() > parsed.e) return { ok: false, reason: 'OTP expired. Request a new code.' };
    const expected = signOtp(mobile, otp, parsed.e);
    const a = Buffer.from(String(parsed.s || ''));
    const b = Buffer.from(expected);
    if (a.length !== b.length || !crypto.timingSafeEqual(a, b)) {
      return { ok: false, reason: 'Invalid OTP code. Please check and try again.' };
    }
    return { ok: true };
  } catch {
    return { ok: false, reason: 'Invalid OTP session. Request a new code.' };
  }
}

export async function POST(req) {
  try {
    const { phone, otp, otpToken } = await req.json();
    if (!phone || !otp) {
      return NextResponse.json({ error: 'Phone and OTP are required' }, { status: 400 });
    }

    const cleanPhone = phone.replace(/\D/g, '');
    const mobile = cleanPhone.length === 10 ? '91' + cleanPhone : cleanPhone;

    if (!MSG91_AUTH_KEY) {
      return NextResponse.json({ error: 'MSG91_AUTH_KEY is not configured on server' }, { status: 500 });
    }

    // ── Step 1: verify the code ─────────────────────────────────────────────
    let verified = false;

    if (otpToken) {
      // Primary path: code was generated by our send-otp and signed into the token.
      const check = verifyOtpToken(otpToken, mobile, String(otp));
      if (!check.ok) {
        return NextResponse.json({ error: check.reason }, { status: 400 });
      }
      verified = true;
    } else {
      // Legacy fallback: MSG91 OTP-service verification (older clients only).
      const url = `https://control.msg91.com/api/v5/otp/verify?otp=${encodeURIComponent(otp)}&mobile=${encodeURIComponent(mobile)}&authkey=${encodeURIComponent(MSG91_AUTH_KEY)}`;
      const res = await fetch(url, { method: 'POST' });
      const data = await res.json();
      if (data.type === 'success' || data.type === '200') {
        verified = true;
      } else {
        return NextResponse.json({ error: data.message || 'Invalid or expired OTP' }, { status: 400 });
      }
    }

    if (!verified) {
      return NextResponse.json({ error: 'OTP verification failed' }, { status: 400 });
    }

    // ── Step 2: mint a real Supabase session ────────────────────────────────
    const db = createWriteClient();
    const userEmail = `${mobile}@quietkeep.com`;

    // 1. Look up existing user by email or phone
    let user = null;
    try {
      const { data: userList } = await db.auth.admin.listUsers();
      user = (userList?.users || []).find(u => u.email === userEmail || u.phone === '+' + mobile);
    } catch (e) {
      console.warn('[verify-otp] listUsers warning:', e);
    }

    // 2. Create user if not existing
    if (!user) {
      try {
        const { data: newUser } = await db.auth.admin.createUser({
          email: userEmail,
          phone: '+' + mobile,
          email_confirm: true,
          user_metadata: { mobile, auth_provider: 'msg91' }
        });
        if (newUser && newUser.user) {
          user = newUser.user;
        }
      } catch (createErr) {
        console.warn('[verify-otp] createUser fallback:', createErr);
      }
    }

    // 3. Mint usable Supabase Session via generateLink -> verifyOtp token exchange
    let session = null;
    try {
      const { data: linkData } = await db.auth.admin.generateLink({
        type: 'magiclink',
        email: userEmail,
      });

      if (linkData?.properties?.hashed_token) {
        const anonClient = createClient(
          process.env.NEXT_PUBLIC_SUPABASE_URL,
          process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
        );
        const { data: verifyData } = await anonClient.auth.verifyOtp({
          token_hash: linkData.properties.hashed_token,
          type: 'magiclink',
        });
        if (verifyData?.session) {
          session = verifyData.session;
        }
      }
    } catch (sessionErr) {
      console.error('[verify-otp] session minting error:', sessionErr);
    }

    return NextResponse.json({
      success: true,
      message: 'OTP verified successfully',
      mobile,
      email: userEmail,
      user_id: user ? user.id : (session ? session.user.id : null),
      session: session ? {
        access_token: session.access_token,
        refresh_token: session.refresh_token,
        expires_in: session.expires_in,
        expires_at: session.expires_at,
        token_type: session.token_type,
        user: session.user
      } : null
    });
  } catch (err) {
    return NextResponse.json({ error: err.message || 'Internal server error' }, { status: 500 });
  }
}
